---
# TU Berlin Service
apiVersion: v1
kind: Service
metadata:
  name: viable-credentials-tub
  namespace: viable-credentials
  labels:
    app: viable-credentials-tub
    tenant: tub
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: viable-credentials-tub
    tenant: tub

---
# FU Berlin Service
apiVersion: v1
kind: Service
metadata:
  name: viable-credentials-fub
  namespace: viable-credentials
  labels:
    app: viable-credentials-fub
    tenant: fub
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: viable-credentials-fub
    tenant: fub

---
# Root Service
apiVersion: v1
kind: Service
metadata:
  name: viable-credentials-root
  namespace: viable-credentials
  labels:
    app: viable-credentials-root
    tenant: root
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: viable-credentials-root
    tenant: root 